### ISSUE TITLE
npm run start fails

### ISSUE THREAD

**Issue by devgeeks** [yuvalsaraf/react-cordova-boilerplate#1]
Calling `npm run start` fails with the message below:

```
npm info it worked if it ends with ok
npm info using npm@2.7.4
npm info using node@v0.12.2
npm info prestart react-cordova-boilerplate@0.0.0
npm info start react-cordova-boilerplate@0.0.0

> react-cordova-boilerplate@0.0.0 start /Users/tommy/src/devgeeks/react-cordova-boilerplate
> better-npm-run start

env: node\r: No such file or directory

npm info react-cordova-boilerplate@0.0.0 Failed to exec start script
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/tommy/.nvm/versions/node/v0.12.2/bin/node" "/Users/tommy/.nvm/versions/node/v0.12.2/bin/npm" "run" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! react-cordova-boilerplate@0.0.0 start: `better-npm-run start`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the react-cordova-boilerplate@0.0.0 start script 'better-npm-run start'.
npm ERR! This is most likely a problem with the react-cordova-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run start
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-cordova-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tommy/src/devgeeks/react-cordova-boilerplate/npm-debug.log
```

And this is the contents of `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/tommy/.nvm/versions/node/v0.12.2/bin/node',
1 verbose cli   '/Users/tommy/.nvm/versions/node/v0.12.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-cordova-boilerplate@0.0.0
6 info start react-cordova-boilerplate@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info react-cordova-boilerplate@0.0.0 Failed to exec start script
9 verbose stack Error: react-cordova-boilerplate@0.0.0 start: `better-npm-run start`
9 verbose stack Exit status 127
9 verbose stack     at EventEmitter.<anonymous> (/Users/tommy/.nvm/versions/node/v0.12.2/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/Users/tommy/.nvm/versions/node/v0.12.2/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid react-cordova-boilerplate@0.0.0
11 verbose cwd /Users/tommy/src/devgeeks/react-cordova-boilerplate
12 error Darwin 14.4.0
13 error argv "/Users/tommy/.nvm/versions/node/v0.12.2/bin/node" "/Users/tommy/.nvm/versions/node/v0.12.2/bin/npm" "run" "start"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error react-cordova-boilerplate@0.0.0 start: `better-npm-run start`
17 error Exit status 127
18 error Failed at the react-cordova-boilerplate@0.0.0 start script 'better-npm-run start'.
18 error This is most likely a problem with the react-cordova-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     better-npm-run start
18 error You can get their info via:
18 error     npm owner ls react-cordova-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by yuvalsaraf** [comment]
Good catch, looks like better-npm-run doesn't work on ubuntu.
Removed it, was too complicated anyway.

Thanks!

**Comment by devgeeks** [comment]
This was on OS X, but the fix still works. Thanks.
